language: node_js
node_js:
- '0.10'
after_success:
- sh ./scripts/deploy.sh
notifications:
  slack:
    secure: jWqLc/ppF5XK10zPo1II/fNFr561CDr4FfFv3J07j5DQR4uiwHe5cD5alHjNPGQta006fTk2eMRkyJ5kAJp60zr13d0ca8bIe/Nerpnl1cw91+t4tT9ZKFQq6Eimqf9wYjS2EHlW/+PH+ctk65z87ffelkdH1+vFXaLWY1VQdv8=
